# Generated by Django 6.0 on 2026-01-13 03:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_grup', models.CharField(max_length=100)),
                ('tipe_grup', models.CharField(choices=[('KELAS', 'Kelas'), ('ORGANISASI', 'Organisasi'), ('KOMUNITAS', 'Komunitas'), ('PROJECT', 'Project Team'), ('LAINNYA', 'Lainnya')], default='KELAS', max_length=20)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tahun_dibuat', models.IntegerField()),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grup Mahasiswa',
                'verbose_name_plural': 'Grup Mahasiswa',
                'ordering': ['-tahun_dibuat', 'nama_grup'],
            },
        ),
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={'ordering': ['nama'], 'verbose_name': 'Mahasiswa', 'verbose_name_plural': 'Mahasiswa'},
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='owner',
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mahasiswa_photos/'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='telepon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='grup',
            field=models.ManyToManyField(blank=True, related_name='mahasiswa', to='mahasiswa.grupmahasiswa'),
        ),
    ]
